// <auto-generated />
namespace R12VIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class requiredfieldsperson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredfieldsperson));
        
        string IMigrationMetadata.Id
        {
            get { return "202308140646391_required fields person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
