//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MR_TARGETS
    {
        public int target_id { get; set; }
        public Nullable<int> province_id { get; set; }
        public Nullable<int> city_municipality_id { get; set; }
        public Nullable<int> target_quantity { get; set; }
        public Nullable<int> barangay_id { get; set; }
    }
}
