//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int ID { get; set; }
        public string UniquePersonID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string ContactNumber { get; set; }
        public string GuardianName { get; set; }
        public string Gender { get; set; }
        public bool isPWD { get; set; }
        public Nullable<int> EthnicGroupID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityMunicipalityID { get; set; }
        public Nullable<int> BarangayID { get; set; }
        public int SiblingRank { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> OccupationID { get; set; }
        public Nullable<int> EducationalAttainmentID { get; set; }
        public Nullable<int> IncomeClassID { get; set; }
    }
}
