//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_VPD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person_VPD()
        {
            this.Vaccination_VPD = new HashSet<Vaccination_VPD>();
        }
    
        public int person_id { get; set; }
        public Nullable<int> person_ethnic_group_id { get; set; }
        public string person_first_name { get; set; }
        public string person_middle_name { get; set; }
        public string person_last_name { get; set; }
        public string person_suffix { get; set; }
        public string person_sex { get; set; }
        public string person_address { get; set; }
        public Nullable<int> person_region_address { get; set; }
        public Nullable<int> person_province_address { get; set; }
        public Nullable<int> person_city_municipality_address { get; set; }
        public Nullable<int> person_barangay_address { get; set; }
        public Nullable<int> person_religion_id { get; set; }
        public Nullable<int> person_parent_occupation_id { get; set; }
        public Nullable<int> person_parent_educational_attainment_id { get; set; }
        public Nullable<int> person_parent_income_class_id { get; set; }
        public Nullable<int> person_sibling_rank { get; set; }
        public Nullable<System.DateTime> person_birth_date { get; set; }
        public Nullable<bool> person_is_pwd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccination_VPD> Vaccination_VPD { get; set; }
    }
}
