//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeniorCitizen_details
    {
        public int sc_id { get; set; }
        public Nullable<int> sc_person_id { get; set; }
        public Nullable<bool> sc_is_sc_member { get; set; }
        public string sc_sc_organization { get; set; }
        public string sc_previous_occupation { get; set; }
        public string sc_contact_person_name { get; set; }
        public string sc_contact_person_relationship { get; set; }
        public string sc_contact_person_contact_number { get; set; }
        public string sc_physician { get; set; }
        public string sc_physician_contact_number { get; set; }
        public string sc_living_arragement { get; set; }
        public string sc_blood_type { get; set; }
        public string sc_disablity { get; set; }
        public string sc_medical_alerts { get; set; }
        public string sc_poverty_reduction_member_id_number { get; set; }
        public Nullable<bool> sc_is_pensioner { get; set; }
        public string sc_pensioner { get; set; }
        public string sc_philhealth_pin { get; set; }
        public string sc_sss_gsis_id_number { get; set; }
    }
}
