//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbSeniorCitizenVacsEntities : DbContext
    {
        public DbSeniorCitizenVacsEntities()
            : base("name=DbSeniorCitizenVacsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SeniorCitizen_details> SeniorCitizen_details { get; set; }
        public virtual DbSet<Vaccination_SC> Vaccination_SC { get; set; }
        public virtual DbSet<Vaccine_SC> Vaccine_SC { get; set; }
    }
}
