//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbR12VISEntities : DbContext
    {
        public DbR12VISEntities()
            : base("name=DbR12VISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Suffix> Suffixes { get; set; }
    
        [DbFunction("DbR12VISEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[DbR12VISEntities].[SplitString](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        [DbFunction("DbR12VISEntities", "GetDashboardData")]
        public virtual IQueryable<GetDashboardData_Result> GetDashboardData(string vaccine_ids, Nullable<int> province_id, Nullable<int> citymun_id, Nullable<int> barangay_id)
        {
            var vaccine_idsParameter = vaccine_ids != null ?
                new ObjectParameter("vaccine_ids", vaccine_ids) :
                new ObjectParameter("vaccine_ids", typeof(string));
    
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            var citymun_idParameter = citymun_id.HasValue ?
                new ObjectParameter("citymun_id", citymun_id) :
                new ObjectParameter("citymun_id", typeof(int));
    
            var barangay_idParameter = barangay_id.HasValue ?
                new ObjectParameter("barangay_id", barangay_id) :
                new ObjectParameter("barangay_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDashboardData_Result>("[DbR12VISEntities].[GetDashboardData](@vaccine_ids, @province_id, @citymun_id, @barangay_id)", vaccine_idsParameter, province_idParameter, citymun_idParameter, barangay_idParameter);
        }
    
        [DbFunction("DbR12VISEntities", "GetBarChartDataFunction")]
        public virtual IQueryable<GetBarChartDataFunction_Result> GetBarChartDataFunction(Nullable<int> dose_id, Nullable<int> province_id, Nullable<int> citymun_id, Nullable<int> barangay_id)
        {
            var dose_idParameter = dose_id.HasValue ?
                new ObjectParameter("dose_id", dose_id) :
                new ObjectParameter("dose_id", typeof(int));
    
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            var citymun_idParameter = citymun_id.HasValue ?
                new ObjectParameter("citymun_id", citymun_id) :
                new ObjectParameter("citymun_id", typeof(int));
    
            var barangay_idParameter = barangay_id.HasValue ?
                new ObjectParameter("barangay_id", barangay_id) :
                new ObjectParameter("barangay_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetBarChartDataFunction_Result>("[DbR12VISEntities].[GetBarChartDataFunction](@dose_id, @province_id, @citymun_id, @barangay_id)", dose_idParameter, province_idParameter, citymun_idParameter, barangay_idParameter);
        }
    
        [DbFunction("DbR12VISEntities", "GetPieChartDataFunction")]
        public virtual IQueryable<GetPieChartDataFunction_Result> GetPieChartDataFunction(Nullable<int> dose_id, string prioritygroup_id, string vaccine_ids, Nullable<int> province_id, Nullable<int> citymun_id, Nullable<int> barangay_id)
        {
            var dose_idParameter = dose_id.HasValue ?
                new ObjectParameter("dose_id", dose_id) :
                new ObjectParameter("dose_id", typeof(int));
    
            var prioritygroup_idParameter = prioritygroup_id != null ?
                new ObjectParameter("prioritygroup_id", prioritygroup_id) :
                new ObjectParameter("prioritygroup_id", typeof(string));
    
            var vaccine_idsParameter = vaccine_ids != null ?
                new ObjectParameter("vaccine_ids", vaccine_ids) :
                new ObjectParameter("vaccine_ids", typeof(string));
    
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            var citymun_idParameter = citymun_id.HasValue ?
                new ObjectParameter("citymun_id", citymun_id) :
                new ObjectParameter("citymun_id", typeof(int));
    
            var barangay_idParameter = barangay_id.HasValue ?
                new ObjectParameter("barangay_id", barangay_id) :
                new ObjectParameter("barangay_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPieChartDataFunction_Result>("[DbR12VISEntities].[GetPieChartDataFunction](@dose_id, @prioritygroup_id, @vaccine_ids, @province_id, @citymun_id, @barangay_id)", dose_idParameter, prioritygroup_idParameter, vaccine_idsParameter, province_idParameter, citymun_idParameter, barangay_idParameter);
        }
    
        [DbFunction("DbR12VISEntities", "PriorityGroupDashboardData")]
        public virtual IQueryable<PriorityGroupDashboardData_Result> PriorityGroupDashboardData(string vaccine_ids, Nullable<int> province_id, Nullable<int> citymun_id, Nullable<int> barangay_id)
        {
            var vaccine_idsParameter = vaccine_ids != null ?
                new ObjectParameter("vaccine_ids", vaccine_ids) :
                new ObjectParameter("vaccine_ids", typeof(string));
    
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            var citymun_idParameter = citymun_id.HasValue ?
                new ObjectParameter("citymun_id", citymun_id) :
                new ObjectParameter("citymun_id", typeof(int));
    
            var barangay_idParameter = barangay_id.HasValue ?
                new ObjectParameter("barangay_id", barangay_id) :
                new ObjectParameter("barangay_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<PriorityGroupDashboardData_Result>("[DbR12VISEntities].[PriorityGroupDashboardData](@vaccine_ids, @province_id, @citymun_id, @barangay_id)", vaccine_idsParameter, province_idParameter, citymun_idParameter, barangay_idParameter);
        }
    }
}
