//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbMRSpecialVacsEntities : DbContext
    {
        public DbMRSpecialVacsEntities()
            : base("name=DbMRSpecialVacsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person_VPD> Person_VPD { get; set; }
        public virtual DbSet<Vaccine_VPD> Vaccine_VPD { get; set; }
        public virtual DbSet<MR_TARGETS> MR_TARGETS { get; set; }
        public virtual DbSet<OPV_TARGETS> OPV_TARGETS { get; set; }
        public virtual DbSet<Vaccination_VPD> Vaccination_VPD { get; set; }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetBarChartIncomeClassData")]
        public virtual IQueryable<GetBarChartIncomeClassData_Result> GetBarChartIncomeClassData(Nullable<int> region_id, Nullable<int> province_id, Nullable<int> cm_id)
        {
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("region_id", region_id) :
                new ObjectParameter("region_id", typeof(int));
    
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            var cm_idParameter = cm_id.HasValue ?
                new ObjectParameter("cm_id", cm_id) :
                new ObjectParameter("cm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetBarChartIncomeClassData_Result>("[DbMRSpecialVacsEntities].[GetBarChartIncomeClassData](@region_id, @province_id, @cm_id)", region_idParameter, province_idParameter, cm_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetBarChartOccupationData")]
        public virtual IQueryable<GetBarChartOccupationData_Result> GetBarChartOccupationData(Nullable<int> region_id, Nullable<int> province_id, Nullable<int> cm_id)
        {
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("region_id", region_id) :
                new ObjectParameter("region_id", typeof(int));
    
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            var cm_idParameter = cm_id.HasValue ?
                new ObjectParameter("cm_id", cm_id) :
                new ObjectParameter("cm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetBarChartOccupationData_Result>("[DbMRSpecialVacsEntities].[GetBarChartOccupationData](@region_id, @province_id, @cm_id)", region_idParameter, province_idParameter, cm_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetBarChartPersonRankData")]
        public virtual IQueryable<GetBarChartPersonRankData_Result> GetBarChartPersonRankData(Nullable<int> region_id, Nullable<int> province_id, Nullable<int> cm_id)
        {
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("region_id", region_id) :
                new ObjectParameter("region_id", typeof(int));
    
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            var cm_idParameter = cm_id.HasValue ?
                new ObjectParameter("cm_id", cm_id) :
                new ObjectParameter("cm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetBarChartPersonRankData_Result>("[DbMRSpecialVacsEntities].[GetBarChartPersonRankData](@region_id, @province_id, @cm_id)", region_idParameter, province_idParameter, cm_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetBarChartReligionData")]
        public virtual IQueryable<GetBarChartReligionData_Result> GetBarChartReligionData(Nullable<int> region_id, Nullable<int> province_id, Nullable<int> cm_id)
        {
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("region_id", region_id) :
                new ObjectParameter("region_id", typeof(int));
    
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            var cm_idParameter = cm_id.HasValue ?
                new ObjectParameter("cm_id", cm_id) :
                new ObjectParameter("cm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetBarChartReligionData_Result>("[DbMRSpecialVacsEntities].[GetBarChartReligionData](@region_id, @province_id, @cm_id)", region_idParameter, province_idParameter, cm_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetDashboardMRSIAData")]
        public virtual IQueryable<GetDashboardMRSIAData_Result> GetDashboardMRSIAData(Nullable<int> region_id)
        {
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("region_id", region_id) :
                new ObjectParameter("region_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDashboardMRSIAData_Result>("[DbMRSpecialVacsEntities].[GetDashboardMRSIAData](@region_id)", region_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetDashboardMRSIADataBarangay")]
        public virtual IQueryable<GetDashboardMRSIADataBarangay_Result> GetDashboardMRSIADataBarangay(Nullable<int> cm_id)
        {
            var cm_idParameter = cm_id.HasValue ?
                new ObjectParameter("cm_id", cm_id) :
                new ObjectParameter("cm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDashboardMRSIADataBarangay_Result>("[DbMRSpecialVacsEntities].[GetDashboardMRSIADataBarangay](@cm_id)", cm_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetDashboardMRSIADataCityMun")]
        public virtual IQueryable<GetDashboardMRSIADataCityMun_Result> GetDashboardMRSIADataCityMun(Nullable<int> province_id)
        {
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDashboardMRSIADataCityMun_Result>("[DbMRSpecialVacsEntities].[GetDashboardMRSIADataCityMun](@province_id)", province_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetDashboardRoutineBarangayData")]
        public virtual IQueryable<GetDashboardRoutineBarangayData_Result> GetDashboardRoutineBarangayData(Nullable<int> cm_id)
        {
            var cm_idParameter = cm_id.HasValue ?
                new ObjectParameter("cm_id", cm_id) :
                new ObjectParameter("cm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDashboardRoutineBarangayData_Result>("[DbMRSpecialVacsEntities].[GetDashboardRoutineBarangayData](@cm_id)", cm_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetDashboardRoutineCityMunData")]
        public virtual IQueryable<GetDashboardRoutineCityMunData_Result> GetDashboardRoutineCityMunData(Nullable<int> province_id)
        {
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDashboardRoutineCityMunData_Result>("[DbMRSpecialVacsEntities].[GetDashboardRoutineCityMunData](@province_id)", province_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetDashboardRoutineProvinceData")]
        public virtual IQueryable<GetDashboardRoutineProvinceData_Result> GetDashboardRoutineProvinceData(Nullable<int> region_id)
        {
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("region_id", region_id) :
                new ObjectParameter("region_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDashboardRoutineProvinceData_Result>("[DbMRSpecialVacsEntities].[GetDashboardRoutineProvinceData](@region_id)", region_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetScheduleData")]
        public virtual IQueryable<GetScheduleData_Result> GetScheduleData(Nullable<int> schedule_is_active)
        {
            var schedule_is_activeParameter = schedule_is_active.HasValue ?
                new ObjectParameter("schedule_is_active", schedule_is_active) :
                new ObjectParameter("schedule_is_active", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetScheduleData_Result>("[DbMRSpecialVacsEntities].[GetScheduleData](@schedule_is_active)", schedule_is_activeParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetRoutineCount")]
        public virtual IQueryable<GetRoutineCount_Result> GetRoutineCount(Nullable<int> vaccine_type_id)
        {
            var vaccine_type_idParameter = vaccine_type_id.HasValue ?
                new ObjectParameter("vaccine_type_id", vaccine_type_id) :
                new ObjectParameter("vaccine_type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRoutineCount_Result>("[DbMRSpecialVacsEntities].[GetRoutineCount](@vaccine_type_id)", vaccine_type_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetRoutineVaccinesProvinceData")]
        public virtual IQueryable<GetRoutineVaccinesProvinceData_Result> GetRoutineVaccinesProvinceData(Nullable<int> region_id)
        {
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("region_id", region_id) :
                new ObjectParameter("region_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRoutineVaccinesProvinceData_Result>("[DbMRSpecialVacsEntities].[GetRoutineVaccinesProvinceData](@region_id)", region_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetRoutineVaccinesBarangayData")]
        public virtual IQueryable<GetRoutineVaccinesBarangayData_Result> GetRoutineVaccinesBarangayData(Nullable<int> citymun_id)
        {
            var citymun_idParameter = citymun_id.HasValue ?
                new ObjectParameter("citymun_id", citymun_id) :
                new ObjectParameter("citymun_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRoutineVaccinesBarangayData_Result>("[DbMRSpecialVacsEntities].[GetRoutineVaccinesBarangayData](@citymun_id)", citymun_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetRoutineVaccinesCityMunData")]
        public virtual IQueryable<GetRoutineVaccinesCityMunData_Result> GetRoutineVaccinesCityMunData(Nullable<int> province_id)
        {
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRoutineVaccinesCityMunData_Result>("[DbMRSpecialVacsEntities].[GetRoutineVaccinesCityMunData](@province_id)", province_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetLineChartVPDVaccinationBarangayData")]
        public virtual IQueryable<GetLineChartVPDVaccinationBarangayData_Result> GetLineChartVPDVaccinationBarangayData(Nullable<int> citymun_id)
        {
            var citymun_idParameter = citymun_id.HasValue ?
                new ObjectParameter("citymun_id", citymun_id) :
                new ObjectParameter("citymun_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetLineChartVPDVaccinationBarangayData_Result>("[DbMRSpecialVacsEntities].[GetLineChartVPDVaccinationBarangayData](@citymun_id)", citymun_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetLineChartVPDVaccinationCityMunData")]
        public virtual IQueryable<GetLineChartVPDVaccinationCityMunData_Result> GetLineChartVPDVaccinationCityMunData(Nullable<int> province_id)
        {
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetLineChartVPDVaccinationCityMunData_Result>("[DbMRSpecialVacsEntities].[GetLineChartVPDVaccinationCityMunData](@province_id)", province_idParameter);
        }
    
        [DbFunction("DbMRSpecialVacsEntities", "GetLineChartVPDVaccinationProvinceData")]
        public virtual IQueryable<GetLineChartVPDVaccinationProvinceData_Result> GetLineChartVPDVaccinationProvinceData(Nullable<int> region_id)
        {
            var region_idParameter = region_id.HasValue ?
                new ObjectParameter("region_id", region_id) :
                new ObjectParameter("region_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetLineChartVPDVaccinationProvinceData_Result>("[DbMRSpecialVacsEntities].[GetLineChartVPDVaccinationProvinceData](@region_id)", region_idParameter);
        }
    }
}
