//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public int ID { get; set; }
        public int PriorityGroupID { get; set; }
        public string Comorbidity { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> DeferralID { get; set; }
        public Nullable<System.DateTime> VaccinationDate { get; set; }
        public int VaccineID { get; set; }
        public string BatchNumber { get; set; }
        public string LotNumber { get; set; }
        public string BakunaCenterCBCRID { get; set; }
        public string VaccinatorName { get; set; }
        public int DoseID { get; set; }
        public Nullable<int> AdverseID { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Adverse Adverse { get; set; }
        public virtual Deferral Deferral { get; set; }
        public virtual Dose Dose { get; set; }
        public virtual Person Person { get; set; }
        public virtual PriorityGroup PriorityGroup { get; set; }
        public virtual User User { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
