//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R12VIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccine_VPD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaccine_VPD()
        {
            this.Vaccination_VPD = new HashSet<Vaccination_VPD>();
        }
    
        public int vaccine_id { get; set; }
        public string vaccine_description { get; set; }
        public Nullable<int> vaccine_created_by { get; set; }
        public Nullable<System.DateTime> vaccine_date_created { get; set; }
        public Nullable<int> vaccine_last_updated_by { get; set; }
        public Nullable<System.DateTime> vaccine_date_last_updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccination_VPD> Vaccination_VPD { get; set; }
    }
}
